---
title: "lab 6"
author: "Alicia Canales"
date: "2023-02-16"
output: 
  html_document:
    code_folding: show
---

```{r setup, include=FALSE, warning =FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning =FALSE, message=FALSE)
```


```{r}
library(tidyverse)
library(janitor)
library(palmerpenguins)

### package for cluster analysis
library(NbClust)
library(factoextra)
library(dendextend)
library(ggdendro)

```

### Intro to cluster analysis - k-means, heirarchical

*Part1 K-mean clustering*
```{r}
ggplot(penguins) +
  geom_point(aes(x = bill_length_mm,
                 y = bill_depth_mm,
                 color = species,
                 shape = sex),
             size = 3,
             alpha = 0.7) + 
  scale_color_manual(values = c('orange', 'cyan4', 'darkmagenta')) # alpha is the transperancy of the dots

ggplot(penguins) + 
  geom_point(aes(x = flipper_length_mm,
                 y = body_mass_g,
                 color = species,
                 shape = sex),
             size = 3,
             alpha = 0.7) +
  scale_color_manual(values = c('orange', 'cyan4', 'darkmagenta')) 

# We now have to pick clusters.. even though we know there are three penguins we should still pick them if we didnt 
```

### Create a complete, scaled version of the data
```{r}
# we are going to drop all rows w NAs
penguins_complete <- penguins %>% 
  drop_na(bill_length_mm, bill_depth_mm, body_mass_g, flipper_length_mm)

penguins_scale <- penguins_complete %>% 
  select(ends_with('_mm'), body_mass_g) %>% 
  scale() # scale is creating a matrix that has a mean of zero and changing the sd = 1. 
```


### Estimate number of clusters
```{r}
number_estimate <- NbClust(penguins_scale, 
                           min.nc = 2, 
                           max.nc = 10, 
                           method = 'kmeans') #min and max c are cluster numbers. testing an algorithm. When the grpahs pop up look for the highest peaks. We see that 5 had tall peaks.. but the results in the consol tells us three? go with majority rule

fviz_nbclust(penguins_scale, FUNcluster = kmeans,
             method = 'wss',
             k.max = 10) # starts to level off around 3, especially after 5
```

### Run some k-means
```{r}
set.seed(123)
penguins_km <- kmeans(penguins_scale,
                      centers = 3,
                      iter.max = 10,
                      nstart = 25) # starting w 3 centers. throwing in the centroids then readjusiting where its going and readjusitng the centroids. its doing it 25 times and spitting out the lowest 

# penguins_km$size
# penguins_km$cluster
penguins_cl <- penguins_complete %>% 
  mutate(cluster_no = factor(penguins_km$cluster)) # have to change it to factors or else r will look at it as a continuous value
```

```{r}
ggplot(penguins_cl) +
  geom_point(aes(x = flipper_length_mm,
                 y = body_mass_g,
                 color = cluster_no,
                 shape = species))

ggplot(penguins_cl) +
  geom_point(aes(x = bill_length_mm,
                 y = bill_depth_mm,
                 color = cluster_no,
                 shape = species)) +
  scale_colour_viridis_d()

penguins_cl %>% 
  select(species, cluster_no) %>% 
table() #putting these results in a table
```
### Hierarchicial Clustering 

#### Start with complete linkage
```{r}
peng_dist <- dist(penguins_scale, method = 'euclidean') 
```





















